### ISSUE TITLE
Handbook 0.0.1 Milestone Proposal

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/organization#26]
### Proposal Title 
Handbook 0.0.1 Milestone Proposal

### Date(s)
01/08/2020

### Category
- [ ] Infrastructure
- [ ] Protocol/Blockchain Dev
- [ ] App Solutions
- [ ] Quality Assurance
- [X] Organization 

### Contract
- [X] This process follows the Milestone Rank Vote Framework as discussed in the Pocket Network Corporation's `Organization Handbook`
- [ ] This process `DOES NOT` follow the Milestone Rank Vote Framework as discussed in the Pocket Network Corporation's `Organization Handbook`

If `DOES NOT` follow the Handbook's Milestone Rank Vote Framework, please describe in detail why below:

#### Context
The PNI Engineering Organization met over the course of 2 weeks to determine it's processes, frameworks and self-identity. These meetings were documented and will be used to create a PNI Handbook, which will serve as the codification of the different processes, frameworks and self-identity documentation that will serve as the basis for all the Organization operations. 

#### Proposal Summary
When executed, this proposal deliverable will be a first version of the Handbook, **Version 0.0.1**, which will serve as the starting point for the Handbook.
