### ISSUE TITLE
Milestone: RC-0.6.0

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/organization#48]
### Leader  
Andrew: CTO
### Date(s)  
01/13/2021
### Category  
- [ ] Infrastructure  
- [X] Protocol/Blockchain Dev  
- [ ] App Solutions  
- [ ] Quality Assurance  
### Contract  
- [X] This process follows the Milestone Framework as discussed in the Pocket Network Corporation's `Organization Handbook`  
- [ ] This process `DOES NOT` follow the Milestone Framework as discussed in the Pocket Network Corporation's `Organization Handbook`  
  
If `DOES NOT` follow the Handbook's Milestone Framework, please describe in detail why below:  
## Original Proposal  
https://github.com/pokt-network/organization/blob/main/proposals/1-08-01-2021/RC-0.6.0.md
## Milestone Short Summary
To frame RC-0.6.0 in a Rank Vote Proposal format, we first must understand the basics of RC-0.6.0 and its importance.

Here are the bullet points of how it improves both the software and the organization

Uses Protobuf encoding instead of amino. This improves both speed, resource consumption and (most importantly) inoperability between languages
Patches the Merkle Tree security hole (won't go into specifics, but a big flaw in the protocol that is exposed)
Contains an upgrade mechanism that can be modeled after in the future
NOTE: this milestone is near completion already, and for reasons explained in the 'contract' section, the details are glossed over
