### ISSUE TITLE
Milestone: Tx Indexer

### ISSUE THREAD

**Issue by edjroz** [pokt-network/organization#50]
### Leader  
Eduardo Diaz Blockchain Engineer
### Date(s)  
01/14/2021
### Category  
- [ ] Infrastructure  
- [X] Protocol/Blockchain Dev  
- [ ] App Solutions  
- [ ] Quality Assurance  
### Contract  
- [X] This process follows the Milestone Framework as discussed in the Pocket Network Corporation's `Organization Handbook`  
- [ ] This process `DOES NOT` follow the Milestone Framework as discussed in the Pocket Network Corporation's `Organization Handbook`  
  
If `DOES NOT` follow the Handbook's Milestone Framework, please describe in detail why below:  
## Original Proposal  
[Tx indexer Proposal](https://github.com/pokt-network/organization/blob/main/proposals/1-08-01-2021/tx-indexer-milestone-proposal.md)

## Milestone Short Summary
The current tx indexer implemented by Tendermint team offers subpar performance by forcing us to load all index keys sort them and then build a page.

The tx indexer should be able to understand the indexes it's going through and be able to build a page without having to load all keys and sorting them.
