### ISSUE TITLE
Milestone: Handbook 0.0.1

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/organization#54]
### Leader  
Luis: CEO 
### Date(s)  
1/19/2021  
### Category  
- [ ] Infrastructure  
- [ ] Protocol/Blockchain Dev  
- [ ] App Solutions  
- [ ] Quality Assurance  
- [ ] Organization
### Contract  
- [X] This process follows the Milestone Framework as discussed in the Pocket Network Corporation's `Organization Handbook`  
- [ ] This process `DOES NOT` follow the Milestone Framework as discussed in the Pocket Network Corporation's `Organization Handbook`  
  
If `DOES NOT` follow the Handbook's Milestone Framework, please describe in detail why below:  
[Detailed Description Of Proposal]  
## Original Proposal  
https://github.com/pokt-network/organization/blob/main/proposals/1-08-01-2021/handbook.md
### Detailed Summary of Proposal  
The PNI Engineering Organization met over the course of 2 weeks to determine it's processes, frameworks and self-identity. These meetings were documented and will be used to create a PNI Handbook, which will serve as the codification of the different processes, frameworks and self-identity documentation that will serve as the basis for all the Organization operations.
